// Weak stubs for non-selftest registration functions.
// Compiled only when EXTERNAL_TEST_DIR is set.  These stubs are overridden
// by strong symbols from the external test suite's compiled objects.
// When no external tests are linked, the stubs are harmless no-ops.

__attribute__((weak)) void register_memory_tests() {}
__attribute__((weak)) void register_ipc_tests() {}
__attribute__((weak)) void register_scheduler_tests() {}
__attribute__((weak)) void register_task_tests() {}
__attribute__((weak)) void register_driver_tests() {}
__attribute__((weak)) void register_vfs_tests() {}
__attribute__((weak)) void register_tmpfs_tests() {}
__attribute__((weak)) void register_tmpfs_invalid_mount_tests() {}
__attribute__((weak)) void register_tmpfs_io_timeout_tests() {}
__attribute__((weak)) void register_tmpfs_corrupted_metadata_tests() {}
__attribute__((weak)) void register_tmpfs_mount_unmount_failure_tests() {}
__attribute__((weak)) void register_signals_tests() {}
__attribute__((weak)) void register_process_tests() {}
__attribute__((weak)) void register_elf_tests() {}
__attribute__((weak)) void register_elf_loader_tests() {}
__attribute__((weak)) void register_fstab_tests() {}
__attribute__((weak)) void register_rtc_tests() {}
__attribute__((weak)) void register_rlimit_tests() {}
__attribute__((weak)) void register_init_tests() {}
__attribute__((weak)) void register_syscall_tests() {}
__attribute__((weak)) void register_sync_tests() {}
__attribute__((weak)) void register_sync_block_pattern_tests() {}
__attribute__((weak)) void register_spinlock_tests() {}
__attribute__((weak)) void register_capability_tests() {}
__attribute__((weak)) void register_task_lifecycle_tests() {}
__attribute__((weak)) void register_idle_task_tests() {}
__attribute__((weak)) void register_zombie_cleanup_tests() {}
__attribute__((weak)) void register_wcet_cleanup_tests() {}
__attribute__((weak)) void register_idle_cleanup_tests() {}
__attribute__((weak)) void register_vfsd_tests() {}
__attribute__((weak)) void register_iocd_tests() {}
__attribute__((weak)) void register_wfg_tests() {}
__attribute__((weak)) void register_deadlock_detect_tests() {}
__attribute__((weak)) void register_deadlock_recovery_tests() {}
__attribute__((weak)) void register_health_tests() {}
__attribute__((weak)) void register_timer_tests() {}
__attribute__((weak)) void register_timing_tests() {}
__attribute__((weak)) void register_serial_tests() {}
__attribute__((weak)) void register_keyboard_tests() {}
__attribute__((weak)) void register_spsc_tests() {}
__attribute__((weak)) void register_preemption_under_syscall_tests() {}
__attribute__((weak)) void register_spinlock_stress_tests() {}
__attribute__((weak)) void register_atomic_context_switch_tests() {}
__attribute__((weak)) void register_bench_syscall_latency_tests() {}
__attribute__((weak)) void register_bench_irq_latency_tests() {}
__attribute__((weak)) void register_gdt_tests() {}
__attribute__((weak)) void register_idt_tests() {}
__attribute__((weak)) void register_exc_table_tests() {}
__attribute__((weak)) void register_bootparams_tests() {}
__attribute__((weak)) void register_multiboot_tests() {}
__attribute__((weak)) void register_address_tests() {}
__attribute__((weak)) void register_pipe_tests() {}
__attribute__((weak)) void register_vfs_internal_tests() {}
__attribute__((weak)) void register_gcov_tests() {}
__attribute__((weak)) void register_debug_tests() {}
__attribute__((weak)) void register_framebuffer_tests() {}
__attribute__((weak)) void register_stress_tests() {}
__attribute__((weak)) void register_pic_tests() {}
__attribute__((weak)) void register_integration_tests() {}
__attribute__((weak)) void register_pml4_clone_tests() {}
__attribute__((weak)) void register_buffer_pool_tests() {}
__attribute__((weak)) void register_ipc_blocking_tests() {}
__attribute__((weak)) void register_vfsd_authorization_tests() {}
__attribute__((weak)) void register_textutils_tests() {}
__attribute__((weak)) void register_irq_guard_tests() {}
__attribute__((weak)) void register_shell_redirect_tests() {}
__attribute__((weak)) void register_klog_tests() {}
__attribute__((weak)) void register_hal_tests() {}
__attribute__((weak)) void register_buildsystem_tests() {}
__attribute__((weak)) void register_secure_exec_tests() {}
__attribute__((weak)) void register_pci_tests() {}
__attribute__((weak)) void register_virtio_tests() {}
__attribute__((weak)) void register_dma_tests() {}
__attribute__((weak)) void register_net_tests() {}
__attribute__((weak)) void register_ipc_benchmark_tests() {}
__attribute__((weak)) void register_ipc_robustness_tests() {}
__attribute__((weak)) void register_syscall_fuzz_tests() {}
__attribute__((weak)) void register_starvation_deadlock_tests() {}
__attribute__((weak)) void register_deadline_miss_tests() {}
__attribute__((weak)) void register_wcet_overrun_tests() {}
__attribute__((weak)) void register_wcet_scheduler_tests() {}
__attribute__((weak)) void register_deadline_action_tests() {}
__attribute__((weak)) void register_ss_deadline_tests() {}
__attribute__((weak)) void register_deadline_recovery_tests() {}
__attribute__((weak)) void register_priority_inheritance_tests() {}
__attribute__((weak)) void register_resource_exhaustion_tests() {}
__attribute__((weak)) void register_microkernel_transition_tests() {}
__attribute__((weak)) void register_random_tests() {}
__attribute__((weak)) void register_random_vfs_tests() {}
__attribute__((weak)) void register_random_syscall_tests() {}
__attribute__((weak)) void register_random_seed_tests() {}
__attribute__((weak)) void register_fpu_tests() {}
__attribute__((weak)) void register_fpu_sse_tests() {}
__attribute__((weak)) void register_fpu_clone_tests() {}
__attribute__((weak)) void register_fpu_multi_tests() {}
__attribute__((weak)) void register_fpu_xmm_all_tests() {}
__attribute__((weak)) void register_random_vfs_write_tests() {}
__attribute__((weak)) void register_ipc_lock_free_tests() {}
__attribute__((weak)) void register_irqguard_audit_tests() {}
__attribute__((weak)) void register_memory_safety_tests() {}
__attribute__((weak)) void register_sporadic_server_tests() {}
__attribute__((weak)) void register_atomic_tests() {}
__attribute__((weak)) void register_cross_arch_tests() {}
#if defined(CONFIG_ARCH_AARCH64)
__attribute__((weak)) void register_aarch64_tests() {}
#endif
#if defined(CONFIG_ARCH_RISCV64)
__attribute__((weak)) void register_riscv64_tests() {}
#endif
__attribute__((weak)) void register_lock_order_tests() {}
__attribute__((weak)) void register_budget_tests() {}
__attribute__((weak)) void register_pip_tests() {}
__attribute__((weak)) void register_pcp_tests() {}
__attribute__((weak)) void register_lock_validator_tests() {}
__attribute__((weak)) void register_mlock_tests() {}
__attribute__((weak)) void register_cpu_load_tests() {}
__attribute__((weak)) void register_slab_reclaim_tests() {}
